export interface Company {
  name: string;
  tier: 1 | 2 | 3;
}

export const TOP_COMPANIES: Company[] = [
  { name: "Tata Consultancy Services (TCS)", tier: 1 },
  { name: "Reliance Industries", tier: 1 },
  { name: "HDFC Bank", tier: 1 },
  { name: "Infosys", tier: 1 },
  { name: "ICICI Bank", tier: 1 },
  { name: "Hindustan Unilever", tier: 1 },
  { name: "State Bank of India (SBI)", tier: 1 },
  { name: "Bharti Airtel", tier: 1 },
  { name: "Bajaj Finance", tier: 1 },
  { name: "Adani Enterprises", tier: 1 },
  { name: "Larsen & Toubro (L&T)", tier: 1 },
  { name: "ITC Limited", tier: 1 },
  { name: "Kotak Mahindra Bank", tier: 1 },
  { name: "Wipro", tier: 1 },
  { name: "HCL Technologies", tier: 1 },
  { name: "Axis Bank", tier: 1 },
  { name: "Maruti Suzuki", tier: 1 },
  { name: "Sun Pharmaceutical", tier: 1 },
  { name: "Titan Company", tier: 1 },
  { name: "UltraTech Cement", tier: 1 },
  { name: "Asian Paints", tier: 1 },
  { name: "NTPC Limited", tier: 1 },
  { name: "Power Grid Corporation", tier: 1 },
  { name: "Tata Steel", tier: 1 },
  { name: "Mahindra & Mahindra", tier: 1 },
  { name: "JSW Steel", tier: 1 },
  { name: "Nestle India", tier: 1 },
  { name: "Coal India", tier: 1 },
  { name: "Hindalco Industries", tier: 1 },
  { name: "Grasim Industries", tier: 1 },
  { name: "Tech Mahindra", tier: 1 },
  { name: "Adani Ports", tier: 1 },
  { name: "IndusInd Bank", tier: 1 },
  { name: "Cipla", tier: 1 },
  { name: "Dr. Reddy's Laboratories", tier: 1 },
  { name: "Apollo Hospitals", tier: 1 },
  { name: "Britannia Industries", tier: 1 },
  { name: "Bharat Petroleum (BPCL)", tier: 1 },
  { name: "Oil & Natural Gas Corporation (ONGC)", tier: 1 },
  { name: "Hero MotoCorp", tier: 1 },
  { name: "Eicher Motors", tier: 1 },
  { name: "Bajaj Auto", tier: 1 },
  { name: "Divi's Laboratories", tier: 1 },
  { name: "UPL Limited", tier: 1 },
  { name: "Shree Cement", tier: 1 },
  { name: "HDFC Life", tier: 1 },
  { name: "SBI Life Insurance", tier: 1 },
  { name: "Adani Green Energy", tier: 1 },
  { name: "Adani Transmission", tier: 1 },
  { name: "Adani Total Gas", tier: 1 },
  { name: "Zomato", tier: 2 },
  { name: "Swiggy", tier: 2 },
  { name: "Paytm", tier: 2 },
  { name: "Ola Cabs", tier: 2 },
  { name: "BYJU'S", tier: 2 },
  { name: "PhonePe", tier: 2 },
  { name: "Razorpay", tier: 2 },
  { name: "CRED", tier: 2 },
  { name: "Dream11", tier: 2 },
  { name: "Postman", tier: 2 },
  { name: "Freshworks", tier: 2 },
  { name: "BrowserStack", tier: 2 },
  { name: "Unacademy", tier: 2 },
  { name: "Pine Labs", tier: 2 },
  { name: "Nykaa", tier: 2 },
  { name: "PolicyBazaar", tier: 2 },
  { name: "Delhivery", tier: 2 },
  { name: "Lenskart", tier: 2 },
  { name: "ShareChat", tier: 2 },
  { name: "Meesho", tier: 2 },
  { name: "Pharmeasy", tier: 2 },
  { name: "Groww", tier: 2 },
  { name: "Upstox", tier: 2 },
  { name: "CoinSwitch Kuber", tier: 2 },
  { name: "CoinDCX", tier: 2 },
  { name: "Spinny", tier: 2 },
  { name: "Cars24", tier: 2 },
  { name: "Droom", tier: 2 },
  { name: "FirstCry", tier: 2 },
  { name: "GlobalBees", tier: 2 },
  { name: "Mamaearth", tier: 2 },
  { name: "Mensa Brand", tier: 2 },
  { name: "MyGlamm", tier: 2 },
  { name: "Purplle", tier: 2 },
  { name: "Sugar Cosmetics", tier: 2 },
  { name: "The Good Glamm Group", tier: 2 },
  { name: "Vedantu", tier: 2 },
  { name: "Eruditus", tier: 2 },
  { name: "Lead School", tier: 2 },
  { name: "PhysicsWallah", tier: 2 },
  { name: "Darwinbox", tier: 2 },
  { name: "Chargebee", tier: 2 },
  { name: "Zenoti", tier: 2 },
  { name: "HighRadius", tier: 2 },
  { name: "Icertis", tier: 2 },
  { name: "Druva", tier: 2 },
  { name: "Mindtickle", tier: 2 },
  { name: "Amagi", tier: 2 },
  { name: "Hasura", tier: 2 },
  { name: "Fractal Analytics", tier: 2 },
  { name: "Mu Sigma", tier: 2 },
  { name: "Absolutdata", tier: 3 },
  { name: "LatentView Analytics", tier: 3 },
  { name: "Tiger Analytics", tier: 3 },
  { name: "Bridgei2i", tier: 3 },
  { name: "Gramener", tier: 3 },
  { name: "Flytxt", tier: 3 },
  { name: "Manthan", tier: 3 },
  { name: "Capillary Technologies", tier: 3 },
  { name: "Unbxd", tier: 3 },
  { name: "Vue.ai", tier: 3 },
  { name: "Mad Street Den", tier: 3 },
  { name: "Yellow.ai", tier: 3 },
  { name: "Haptik", tier: 3 },
  { name: "Gupshup", tier: 3 },
  { name: "Route Mobile", tier: 3 },
  { name: "Tanla Platforms", tier: 3 },
  { name: "Affle", tier: 3 },
  { name: "InMobi", tier: 3 },
  { name: "Glance", tier: 3 },
  { name: "Roposo", tier: 3 },
  { name: "Dailyhunt", tier: 3 },
  { name: "Josh", tier: 3 },
  { name: "Moj", tier: 3 },
  { name: "Tiki", tier: 3 },
  { name: "Chingari", tier: 3 },
  { name: "Mitron", tier: 3 },
  { name: "Trell", tier: 3 },
  { name: "Bulbul", tier: 3 },
  { name: "Simsim", tier: 3 },
  { name: "GlowRoad", tier: 3 },
  { name: "Shop101", tier: 3 },
  { name: "DealShare", tier: 3 },
  { name: "CityMall", tier: 3 },
  { name: "Mall91", tier: 3 },
  { name: "ElasticRun", tier: 3 },
  { name: "Ninjacart", tier: 3 },
  { name: "WayCool", tier: 3 },
  { name: "DeHaat", tier: 3 },
  { name: "AgroStar", tier: 3 },
  { name: "Gramophone", tier: 3 },
  { name: "Bijak", tier: 3 },
  { name: "Crofarm", tier: 3 },
  { name: "Otipy", tier: 3 },
  { name: "Fraazo", tier: 3 },
  { name: "Dunzo", tier: 3 },
  { name: "Zepto", tier: 3 },
  { name: "Blinkit", tier: 3 },
  { name: "BigBasket", tier: 3 },
  { name: "MilkBasket", tier: 3 },
  { name: "Country Delight", tier: 3 },
  { name: "Licious", tier: 3 },
  { name: "FreshToHome", tier: 3 },
  { name: "Zappfresh", tier: 3 },
  { name: "Tendercut", tier: 3 },
  { name: "Meatigo", tier: 3 },
  { name: "GoodDot", tier: 3 },
  { name: "Imagine Meats", tier: 3 },
  { name: "Blue Tribe", tier: 3 },
  { name: "Greenest", tier: 3 },
  { name: "Vezlay", tier: 3 },
  { name: "Urban Company", tier: 3 },
  { name: "Housejoy", tier: 3 },
  { name: "Zimmber", tier: 3 },
  { name: "Timesaverz", tier: 3 },
  { name: "Mr. Right", tier: 3 },
  { name: "Taskbob", tier: 3 },
  { name: "LocalOye", tier: 3 },
  { name: "Nearbuy", tier: 3 },
  { name: "Little", tier: 3 },
  { name: "Magicpin", tier: 3 },
  { name: "Dineout", tier: 3 },
  { name: "EazyDiner", tier: 3 },
  { name: "Zomato Gold", tier: 3 },
  { name: "Swiggy One", tier: 3 },
  { name: "Amazon Prime", tier: 3 },
  { name: "Flipkart Plus", tier: 3 },
  { name: "Tata Neu", tier: 3 },
  { name: "JioMart", tier: 3 },
  { name: "Reliance Digital", tier: 3 },
  { name: "Croma", tier: 3 },
  { name: "Vijay Sales", tier: 3 },
  { name: "Sangeetha Mobiles", tier: 3 },
  { name: "Poorvika", tier: 3 },
  { name: "Big C", tier: 3 },
  { name: "Lot Mobiles", tier: 3 },
  { name: "Happi Mobiles", tier: 3 },
  { name: "Spice Hotspot", tier: 3 },
  { name: "UniverCell", tier: 3 },
  { name: "MobileStore", tier: 3 },
  { name: "eZone", tier: 3 },
  { name: "Next", tier: 3 },
  { name: "Aditya Birla Fashion", tier: 3 },
  { name: "Shoppers Stop", tier: 3 },
  { name: "Lifestyle", tier: 3 },
  { name: "Westside", tier: 3 },
  { name: "Pantaloons", tier: 3 },
  { name: "Max Fashion", tier: 3 },
  { name: "Reliance Trends", tier: 3 },
  { name: "fbb", tier: 3 },
  { name: "Brand Factory", tier: 3 },
  { name: "Central", tier: 3 },
  { name: "Globus", tier: 3 }
];
